apiVersion: v1
kind: ReplicationController
metadata:
  name: grpc-car
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grpc-car
    spec:
      containers:
        - name: grpc-car-container
          image: kamaal0/grpc_car:0.0.3
          env:
            - name:  "DB_HOST"
              value: "mongodb://mongo:27017/cars"
          ports:
            - containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    name: grpc-api
  type: NodePort
  ports:
    - name: http
      nodePort: 30005
      port: 80
      targetPort: 5003
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: car
spec:
  selector:
    name: grpc-car
  type: NodePort
  ports:
    - name: http
      nodePort: 30006
      port: 50051
      targetPort: 50051
      protocol: TCP
